#!/bin/bash
# Standalone IB Gateway Installation and Configuration Script
# This script is completely self-contained and requires no external configuration files
# It will install IB Gateway, configure IBC, and set up a systemd service

set -e

# ============================================================================
# CONFIGURATION - Modify these variables if needed
# ============================================================================
IB_GATEWAY_VERSION="1037"
IBC_VERSION="3.23.0"
INSTALL_DIR="$HOME/Jts"
IBC_DIR="$HOME/ibc"
API_PORT="4002"
CLIENT_ID="1"

# ============================================================================
# COMMAND LINE ARGUMENTS & USER PROMPTS
# ============================================================================
TRADING_MODE="${1:-paper}"

echo "=========================================="
echo "IB Gateway Standalone Setup Script"
echo "=========================================="
echo "This script will:"
echo "  - Install all prerequisites"
echo "  - Download and install IB Gateway"
echo "  - Download and configure IBC (automation tool)"
echo "  - Create all necessary configuration files"
echo "  - Set up systemd service for auto-start"
echo ""

# Validate trading mode
if [ "$TRADING_MODE" != "paper" ] && [ "$TRADING_MODE" != "live" ]; then
    echo "ERROR: Trading mode must be 'paper' or 'live'"
    echo "Usage: $0 [paper|live]"
    exit 1
fi

# Prompt for username and password securely
echo "Please enter your IBKR credentials:"
read -p "IBKR Username: " USERNAME
read -s -p "IBKR Password: " PASSWORD
echo ""
echo ""

# Validate credentials
if [ -z "$USERNAME" ] || [ -z "$PASSWORD" ]; then
    echo "ERROR: Username and password cannot be empty"
    exit 1
fi

echo "Configuration:"
echo "  Username: $USERNAME"
echo "  Trading Mode: $TRADING_MODE"
echo "  API Port: $API_PORT"
echo "  IB Gateway Version: $IB_GATEWAY_VERSION"
echo "  IBC Version: $IBC_VERSION"
echo "  Install Directory: $INSTALL_DIR"
echo "  IBC Directory: $IBC_DIR"
echo ""
read -p "Press Enter to continue or Ctrl+C to cancel..."
echo ""

# Install prerequisites
echo "=== Installing prerequisites ==="
sudo apt-get update
sudo apt-get install -y wget unzip xvfb libxtst6 libxrender1 libxi6 openjdk-11-jre

# Download and install IB Gateway
echo "=== Downloading IB Gateway ==="
cd /tmp
if [ -f "ibgateway-stable-standalone-linux-x64.sh" ]; then
    echo "  Removing old installer..."
    rm -f ibgateway-stable-standalone-linux-x64.sh
fi

echo "  Downloading from IBKR servers (301MB - may take several minutes)..."
wget --progress=dot:giga https://download2.interactivebrokers.com/installers/ibgateway/stable-standalone/ibgateway-stable-standalone-linux-x64.sh

if [ ! -f "ibgateway-stable-standalone-linux-x64.sh" ]; then
    echo "ERROR: Download failed"
    exit 1
fi

chmod +x ibgateway-stable-standalone-linux-x64.sh
echo "  Download complete"

echo "=== Installing IB Gateway (silent installation) ==="
mkdir -p "$INSTALL_DIR/ibgateway"
./ibgateway-stable-standalone-linux-x64.sh -q -dir "$INSTALL_DIR/ibgateway/$IB_GATEWAY_VERSION" &
INSTALL_PID=$!

echo "  Installation in progress (PID: $INSTALL_PID)..."
wait $INSTALL_PID
INSTALL_EXIT_CODE=$?

if [ $INSTALL_EXIT_CODE -ne 0 ]; then
    echo "ERROR: Installation failed with exit code $INSTALL_EXIT_CODE"
    exit 1
fi

echo "  IB Gateway installation complete"

# Download and install IBC
echo "=== Downloading IBC ==="
if [ -f "IBCLinux-$IBC_VERSION.zip" ]; then
    rm -f "IBCLinux-$IBC_VERSION.zip"
fi

echo "  Downloading IBC version $IBC_VERSION from GitHub..."
wget --progress=dot:giga https://github.com/IbcAlpha/IBC/releases/download/$IBC_VERSION/IBCLinux-$IBC_VERSION.zip

if [ ! -f "IBCLinux-$IBC_VERSION.zip" ]; then
    echo "ERROR: IBC download failed"
    exit 1
fi

echo "  Extracting IBC files..."
mkdir -p "$IBC_DIR"
unzip -q IBCLinux-$IBC_VERSION.zip -d "$IBC_DIR"
echo "  IBC installation complete"

# ============================================================================
# Create IBC configuration file (generated from embedded template)
# ============================================================================
echo "=== Creating IBC configuration file ==="
mkdir -p "$IBC_DIR"
cat > "$IBC_DIR/config.ini" << EOF
# IBC Configuration File - Auto-generated by setup script
# DO NOT EDIT - This file is generated automatically

FIX=no

# Authentication Settings
IbLoginId=$USERNAME
IbPassword=$PASSWORD

FIXLoginId=
FIXPassword=
SecondFactorDevice=
ReloginAfterSecondFactorAuthenticationTimeout=no
SecondFactorAuthenticationExitInterval=
SecondFactorAuthenticationTimeout=180
ExitAfterSecondFactorAuthenticationTimeout=no

# Trading Mode
TradingMode=$TRADING_MODE
AcceptNonBrokerageAccountWarning=yes
LoginDialogDisplayTimeout=60

# TWS Startup Settings
IbDir=
StoreSettingsOnServer=
MinimizeMainWindow=no
ExistingSessionDetectedAction=manual
OverrideTwsApiPort=$API_PORT
OverrideTwsMasterClientID=
ReadOnlyLogin=no
ReadOnlyApi=no

# TWS Auto-Restart Settings
AutoLogoffTime=
AutoRestartTime=
ColdRestartTime=
ClosedownAt=

# Other Settings
AcceptIncomingConnectionAction=accept
AllowBlindTrading=no
SaveTwsSettingsAt=
ConfirmCryptoCurrencyOrders=manual
DismissPasswordExpiryWarning=no
DismissNSEComplianceNotice=yes

# Command Server Settings
CommandServerPort=0
ControlFrom=
BindAddress=
CommandPrompt=
SuppressInfoMessages=yes

# Diagnostic Settings
LogStructureScope=known
LogStructureWhen=never
EOF

echo "  Created: $IBC_DIR/config.ini"

# ============================================================================
# Create gateway startup script (embedded in this script)
# ============================================================================
echo "=== Creating gateway startup script ==="
cat > "$IBC_DIR/gatewaystart.sh" << EOF
#!/bin/bash
# IB Gateway Startup Script - Auto-generated by setup script

IBC_PATH=$IBC_DIR
TWS_PATH=$INSTALL_DIR
TWS_VERSION=$IB_GATEWAY_VERSION
IBC_JAR=\$IBC_PATH/IBC.jar
TWS_CONFIG_PATH=\$IBC_PATH

java -cp \$IBC_JAR ibcalpha.ibc.IbcTws \$TWS_VERSION --gateway --tws-path=\$TWS_PATH --ibc-path=\$IBC_PATH --ibc-ini=\$TWS_CONFIG_PATH/config.ini --mode=$TRADING_MODE --on2fatimeout=exit
EOF

chmod +x "$IBC_DIR/gatewaystart.sh"
echo "  Created: $IBC_DIR/gatewaystart.sh"

# ============================================================================
# Create systemd service file (embedded in this script)
# ============================================================================
echo "=== Creating systemd service ==="
sudo tee /etc/systemd/system/ibgateway.service > /dev/null << EOF
[Unit]
Description=IBKR Gateway with IBC
After=network.target

[Service]
Type=simple
User=$USER
WorkingDirectory=$IBC_DIR
Environment="DISPLAY=:99"
ExecStart=/usr/bin/xvfb-run -a $IBC_DIR/gatewaystart.sh -inline
Restart=on-failure
RestartSec=30

[Install]
WantedBy=multi-user.target
EOF

echo "  Created: /etc/systemd/system/ibgateway.service"

# Reload systemd and enable service
echo "=== Enabling IB Gateway service ==="
sudo systemctl daemon-reload
sudo systemctl enable ibgateway.service

# Clean up
echo "=== Cleaning up ==="
rm -f /tmp/ibgateway-stable-standalone-linux-x64.sh
rm -f /tmp/IBCLinux-$IBC_VERSION.zip

echo ""
echo "=========================================="
echo "Installation Complete!"
echo "=========================================="
echo ""
echo "IB Gateway has been installed and configured as a systemd service."
echo ""
echo "Installation Summary:"
echo "  IB Gateway:       $INSTALL_DIR/ibgateway/$IB_GATEWAY_VERSION"
echo "  IBC Directory:    $IBC_DIR"
echo "  Configuration:    $IBC_DIR/config.ini"
echo "  Service File:     /etc/systemd/system/ibgateway.service"
echo "  API Port:         $API_PORT"
echo "  Trading Mode:     $TRADING_MODE"
echo ""
echo "Service Management:"
echo "  Start:    sudo systemctl start ibgateway"
echo "  Stop:     sudo systemctl stop ibgateway"
echo "  Restart:  sudo systemctl restart ibgateway"
echo "  Status:   sudo systemctl status ibgateway"
echo "  Logs:     journalctl -u ibgateway -f"
echo ""
echo "The service is enabled and will start automatically on system reboot."
echo "To start it now, run: sudo systemctl start ibgateway"
echo ""
echo "Note: It may take 30-60 seconds for the gateway to fully start and accept API connections."
echo ""
